services:
  db:
      image: postgres 
      restart: always
      ports:
          - "5432:5432"
      environment:
          POSTGRES_USER: heat
          POSTGRES_PASSWORD: heat
          POSTGRES_DB: heatdb